name: Task
description: Capture an actionable task with a clear next action
title: "[TASK] "
labels: ["type:task"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      options: [career, learning, health, finance, music, life, work]
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: ["p:high", "p:mid", "p:low"]
    validations:
      required: true
  - type: dropdown
    id: timebox
    attributes:
      label: Timebox (estimate)
      options: [15m, 30m, 60m, 2h, 4h, 1d+]
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: What (Outcome)
      description: What will be true when this is done?
      placeholder: e.g., "Set up Project views for LIFE repo"
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why (Reason)
      description: Why does this matter now?
    validations:
      required: false
  - type: textarea
    id: next_action
    attributes:
      label: Next action (single step)
      description: The smallest possible next step
      placeholder: e.g., "Create Project v2 named LIFE and add views"
    validations:
      required: true
  - type: textarea
    id: dod
    attributes:
      label: Definition of Done
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Notes / Links
    validations:
      required: false
