name: Weekly Priority
description: Define priorities for this week (created during weekly review)
title: "[WEEK] "
labels: ["type:decision", "area:life", "p:high"]
body:
  - type: input
    id: week
    attributes:
      label: Week
      description: e.g., 2026-W06
      placeholder: "2026-W06"
    validations:
      required: true
  - type: textarea
    id: theme
    attributes:
      label: Theme (one sentence)
      placeholder: e.g., "Make the weekly review effortless and consistent"
    validations:
      required: true
  - type: textarea
    id: outcomes
    attributes:
      label: 1–3 Outcomes (must finish)
      placeholder: |
        - Outcome 1:
        - Outcome 2:
        - Outcome 3:
    validations:
      required: true
  - type: textarea
    id: must_do
    attributes:
      label: Must-do tasks (3–7)
      placeholder: |
        - [ ] Task A
        - [ ] Task B
    validations:
      required: true
  - type: textarea
    id: not_doing
    attributes:
      label: Not doing (stop list)
    validations:
      required: false
  - type: textarea
    id: risks
    attributes:
      label: Risks / blockers
    validations:
      required: false
